### ISSUE TITLE
Run backstop server on a different port

### ISSUE THREAD

**Issue by shankarsridhar** [garris/ember-backstop#34]
Is there a way to run backstop server on a different port other than the default 3000 ?

I'll be happy to send a PR for the same, if it's not possible already.

**Comment by garris** [comment]
Oh yeah,  please send PR for that!  Desperately needed.  Prolly default to 3000 but overrideable with backstopPort env var?   Is that what you are thinking?

**Comment by shankarsridhar** [comment]
> Oh yeah, please send PR for that! Desperately needed. Prolly default to 3000 but overrideable with backstopPort env var? Is that what you are thinking?

That's exactly what I had in mind. Will send a PR for it soon.

**Comment by Sticksword** [comment]
Hmm just bumping for awareness, I don't think this issue was fixed in the mentioned PR

**Comment by kiwi-josh** [comment]
I believe this can be closed now - as latest master has this PR merged: https://github.com/garris/ember-backstop/pull/69
You can set the port using this environment variable: `BACKSTOP_REMOTE_HTTP_PORT`

**Comment by kiwi-josh** [comment]
CC @garris 😄
