### ISSUE TITLE
Checkboxes or Radio boxes "checked" state is not preseved

### ISSUE THREAD

**Issue by vgrinko** [garris/ember-backstop#41]
Hello,

I am seeing that checkboxes/radios in Testem are checked, but they are not checked on final screenshots.
it looks like Backstop Ember plugin copies `input.value` for inputs, but not `input.checked` attribute in `prepareInputValuesForCopying`

**Comment by garris** [comment]
Great catch!  I would gladly accept a PR for this if you have the time.  Cheers!
