### ISSUE TITLE
404 error for http://backstopjs.org in the README under `More Info` section

### ISSUE THREAD

**Issue by shankarsridhar** [garris/ember-backstop#5]
In the `More Info` section of README, the link with text, `http://backstopjs.org` is pointing to `https://github.com/garris/ember-backstop/blob/master` that results in a 404 error.

![image](https://user-images.githubusercontent.com/4473214/62414992-e967c980-b5d7-11e9-9208-406c64fa7a1d.png)

I would imagine that this link should probably be pointing to `http://backstopjs.org` or `https://github.com/garris/BackstopJS/blob/master/README.md`.

I will be happy to submit a PR.

**Comment by garris** [comment]
Oh yes.  I would pull that right away.  Thank you.

**Comment by shankarsridhar** [comment]
Looks like this is not an issue anymore.
