### ISSUE TITLE
Dynamically configure scenario settings on per test basis in Ember.

### ISSUE THREAD

**Issue by edeis53** [garris/ember-backstop#8]
We have some tests where we want to configure `misMatchThreshold` separately from the rest of the test suite in Ember. 

It looks like BackstopJS/Remote/index.js is hard coded to pull the first scenario.
https://github.com/garris/BackstopJS/blob/11634c9cc7db73fa8f6a64035d31ab4c49b600ae/remote/index.js#L41
`var s = config.scenarios[0];`

What do you think of passing the scenario config settings dynamically with something like this?

**BackstopJS/Remote/index.js L41**
```
      var s = _merge({}, config.scenarios[0], req.body.scenarioConfig);
```

**ember-backstop/addon-test-support/backstop.js**
```
  const payload = JSON.stringify({
    content,
    name: name,
    widths: options.widths,
    breakpoints: options.breakpoints,
    enableJavaScript: options.enableJavaScript,
    testHash: testHash,
    origin: ORIGIN,
    scenarioConfig: options.scenario
  });
```

**Implementation**
```
    await backstop(
      assert,
      {
        scenario: {
            misMatchThreshold: 0.5
        }
      },
```

**Comment by edeis53** [comment]
Just two line changes and produces a lots of developer ergonomics.

**Comment by edeis53** [comment]
@garris would you accept a pull request for this?

**Comment by garris** [comment]
So sorry for the delay.  Yes.  I would absolutely pull that.  How about just calling the property `scenario` instead of `scenarioConfig`?

**Comment by edeis53** [comment]
@garris pull requests in!

**Comment by garris** [comment]
Ok, everything is bumped and pushed out to NPM.   I am getting GH notifications now so I'll be faster to respond 😀.     Cheers!

**Comment by garris** [comment]
whoops looking into an issue with this.  seems that this isn't working as expected...
`var s = _merge({}, config.scenarios[0], req.body.scenarioConfig);`

**Comment by garris** [comment]
ok fixed. this feature is cool!  

Was able to pass a selector through the assert...
```
    await backstop(assert, {scenario: {selectors: '.jumbo'}});
```
produced this test...

![image](https://user-images.githubusercontent.com/447033/64068651-e15b7380-cbef-11e9-9f7e-fe94dcfe8d72.png)

**Comment by garris** [comment]
Would be awesome if someone could help add the {options} definition to the documentation.

Will try to get to this myself if no one else can get to it.  Cheers!
